version: '3'

tasks:
  default:
    desc: Default task
    cmds:
      - echo "Running default task"

  pull:
    desc: Pull tamplates
    cmds:
      - python3 bulk_clone_repos.py
  gen_nuclei:
    desc: Generate nuclei templates
    cmds:
      - python3 generate_taskfile.py

  remove_dup_splits:
    desc: Remove duplicate splits
    cmds:
      - python3 remove_duplicated_templates.py

  all:
    desc: Pull templates and remove duplicates
    cmds:
      - task: pull
      - task: remove_dup_splits
      - task: gen_nuclei
  clean:
    desc: Clean build artifacts
    cmds:
      - echo "Cleaning..."